### ISSUE TITLE
Preds is Nan

### ISSUE THREAD

**Issue by muyuuuu** [isaaccorley/dfc2022-baseline#1]
Hello, I have runned baseline in my loacl, but found the output of model is nan. Have you encountered this problem? Is it possible that there is a operating system or environmental problem?

Before this line, print the preds get nan.

https://github.com/isaaccorley/dfc2022-baseline/blob/d01e78ee0efd2d286e67a28dff4b506a50b3e897/src/trainer.py#L19

**Comment by muyuuuu** [comment]
![image](https://user-images.githubusercontent.com/43681138/149800420-8355239e-f00a-441f-9db8-954f8bd213a4.png)

**Comment by isaaccorley** [comment]
What OS and config are you using?

**Comment by muyuuuu** [comment]
> What OS and config are you using?

```
OS: windows10
conda: 4.10.3
python: 3.7.11
and pip list:
```

![image](https://user-images.githubusercontent.com/43681138/149861338-856a6239-1ddd-4a16-869a-d97332be39bb.png)

config file is from: https://github.com/isaaccorley/dfc2022-baseline/blob/master/conf/dfc2022.yaml , I didn't change anything.

Is it possible that the problem is data folder? the structure of my data directory is:

```
data/
    labeled_train/
    unlabeled_train/
    val/
```

The tif files at BDORIHO folder (view at windows10):

![image](https://user-images.githubusercontent.com/43681138/149862534-c6b49863-fad2-4223-b628-97d788f35c56.png)

The tif files at RGEALTI folder (view at windows10). But the tif files at RGEALTI folder (view in linux) is black.

![image](https://user-images.githubusercontent.com/43681138/149862253-5d5d971d-aaf5-469b-8271-393ec9b449cc.png)

The tif files at  UrbanAtlas folder (view at windows10):

![image](https://user-images.githubusercontent.com/43681138/149862660-28c498c9-d48b-4b1e-8d8b-b47c59162eb7.png)

**Comment by isaaccorley** [comment]
I don't think it's related to the data. I'm using the latest versions of pytorch lighting torch and torchvision with cuda 11. If I had to guess it's probably package related. I haven't tested this on windows.

**Comment by muyuuuu** [comment]
> I don't think it's related to the data. I'm using the latest versions of pytorch lighting torch and torchvision with cuda 11. If I had to guess it's probably package related. I haven't tested this on windows.

Thanks for your help. I will update cuda from 10 to 11, I Will be back after this to show the results.

**Comment by muyuuuu** [comment]
> I'm using the latest versions of pytorch lighting torch and torchvision with cuda 11.

A question, what's your torch, torchvision and pytorch lighting version?

**Comment by muyuuuu** [comment]
Install the latest version of torch(1.9.0+cu111), torchvision(0.10.0+cu111), the problem has been fixed. Thank you.

**Comment by hushuai1** [comment]
> Install the latest version of torch(1.9.0+cu111), torchvision(0.10.0+cu111), the problem has been fixed. Thank you.

hello I get some error on install torchgeo0.3.0,  it seemed that the torchgeo0.2.0 don't support DFC2022 dataset .so I clone the git and try to install the follows the error:  
![image](https://user-images.githubusercontent.com/43898397/151124866-e35e955b-f6c3-4b56-b882-a089ccaeb3dc.png)
